version: "3"
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PWD=${MONGO_PWD}
            - SESSION_SECRET=${SESSION_SECRET}
            - DEBUG=node-app:*
        command: node index.js
    nginx:
        ports:
            - "80:80"
    mongodb:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}

    